### ISSUE TITLE
您好，问一下这门课作业需要的测试数据是在哪里下的?

### ISSUE THREAD

**Issue by wind-liang** [qhan1028/Machine-Learning#1]
PPT 里边这个地址 https://inclass.kaggle.com/c/ml2017-hw1-pm2-5 注册了也不能下载，可以给我数据吗？谢谢！

**Comment by qhan1028** [comment]
https://drive.google.com/open?id=0B1zzyklRnKQEQkl4a3hsRkx2WXc

**Comment by VictorQianWan** [comment]
谢谢

**Comment by qhan1028** [comment]
https://drive.google.com/file/d/0B1zzyklRnKQEQkl4a3hsRkx2WXc/view?usp=sharing

請服用
祝你訓練順利

Qhan

2017-12-21 19:34 GMT+08:00 VictorQianWan <notifications@github.com>:
